language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis poetry
script: tox
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  edge: true
  script: poetry publish
  on:
    tags: true
    python: 3.8
env:
  global:
  - secure: OTgG4cNxQzGXRbh4Pa8m6Mmtw+TgJ5MaV9xOKepsoHlvWsYy46SQh+huMTLjNVSQhBTBJYPSsZKP64SSFliLVp7kT1+cds4QaEwTz7OeIK2irkm3WYOPqnd9PIAvCRipV9DTTOZD1Y7RflMIEi8A9gyJSkkZu+7V175/15HngRVS/cQGOhLMI5At/a5NOLuiCczHqNUoP21WtFW6uUWOQmvfnEIZHlZc2nL60CrZLH6gmpy9uU8H/IhHhYmdyACkZ/tR6wYRkVDwtJFsZ8it5eEm1HmGvejoAlPE12GVzxJtnHu2tvEwSiK9T+X0jtIvPzPysHPX2/4pPQn+onNm8Qd55FuaLmeA/vfam7CxlqS543/WnPYE32z2RE5kL8iuXuOUuA4gQzESWyqveqbqAODTlSZB4zYSmpshmvoSJPEG3i+sZT2jLTkrgxJ7EA8hWj3HMgsUU/lQZhAFQ1cZHOoNfv4ggozTqIEl3tynWOEoB/gIEJ0ppK9DKG76CLXFJWmhMAFfc+aIgxE2p3kRWPI8hpmP5yYjQ6Uky3VoBKouTpHYAxi7vrSmtdNQ3sIOfjdaVIL5LFVPLXRVa4ffIyZaNjTn+HvP24Q2HbHLgL8lyCJWgxuxdJWJu960aKgjVJ6esn7OHjMx+gRhLqmgQmphs9UFfRbEVEsEGdmbvXY=
  - secure: iFpQJKuyxjENtUm1ua/vgDf/T4/HaNYISoCJ8Lr5C0ZXT6Kg1Sb8stTATfP+BkapUe+M3PiP7RYNEzxtcPrJLs42fzNjxjiLtB8kIiil5vI+G/+r9iRZuAtqAGF5uCfo+RZfjGbLYxb7/Z1LBHplw7lSkgIg+QDIL0kOJBIWWxUvRYjKTtGEQbeic9p61xOTIw4gNDU7C50foAe2myrNY4hd8BxO8SU0EIm9T5BW3MEg43SKnM4cTvkFUidJ6EQ7IZHbcJEkLGaGZSxcPLf7KgxDDUf196ai3qO2oIJBMtrhQZD/TXjU/vH0qcXAikmwRyYpMd1njV0pWKI2c1Ywuua4JYJHErIaupFyZXpyZiuHtmwEVG3h2iyzb1CFsFjxuzjDyuWP+xPvlvriDrbj22iG4bKcmOB75L4Lblrd7hiXNtSpoOqv4i6N2LiAQjt6MZarF2j2dhGPmv7wjZyGk8r1t+eUplpWP6wYuNkgLnNMHs+GiIxuxVeIgkAHGov3ckZNxF6SPF4eatSAMgAMPniWUr5HSPRHuObtlNHJXXdd/UH2CfXyoVz8EsDgNnsw3UEE7NNnHwIfF9iObEh44zRpUoNJaPjXi2OIlU40FjviXXDkLovPTOjtqeukUst7zG9rKIJvGqvhL9Ch7HU/a71Z10Jd0k1OVjRxXC1fiqo=
  