language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis poetry
script: tox
before_deploy:
- poetry build
deploy:
  provider: pypi
  edge: true
  on:
    tags: true
    python: 3.8
  username: __token__
  password:
    secure: iaNHHJQm6lnbc1fRnSJxrZWMUUdqnDjnhdBmnSg8QwxN1+ZVA2rgKVFqpf1cFNDQ5MebRZA7WeTn8bvFLFa40KyEJYIcZm24QHOZcuoMvwgySekLa/Ax/Mg88qPZjMR8ry/dosWPT6PKB/1Vg/STkgPV+Tvt+SPcqrCZzJGwYRyr6w3YtX7Q2645eV9TYhYPj0J5IClSW2NrP5QM6JJegtNFjXm+mjVQ0W3eFGEIr3rr6VMqtgAXGrdNBOZY09VNy4kmRsy3eqTFmkQjtBP15LJYpqFM096BcLuxoDOz6CTAs+qp6pSOQuCIXtGDHt412skBdLJyMvCvnf3msnqMDrvFJIz1ggO2Xv6V5iEA/84QFEA3539B3BxNT732v+PRlRZwwu218g7TAtWmhrHqRmqi/m7gSYJjApZpPM4UpA8I2PJx8coFnSFq2OH2CQ0Cb7JFF1GXTEdGdEBJE1pQtKTa6PCioNF6QnBEwuKWxYnBLICpK493bMSRn1IzZuFOxEcGbLdxFRT3Cg30uR7LK3446RLaNIiPO0H7GQ9BJ+DTyzaPY4/dVlNsgGIjY9YlhIDVQu0GSNRoKM5eroP7nl1jVF3zOEOJpQ0AtcKxbDPRnK9f0BCeIJ2+MnqCyHR5iKk9clLTo6CpGWAF/13Qb/5IUY5VHQhaZDDvzyLCRPU=
